<a href="https://colab.research.google.com/github/VattamYasritha/Deep_Learning/blob/main/Experiment%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(output):
    return output * (1 - output)

In [3]:
# Input
x = np.array([[1, 0]])

# Target
y = np.array([[1]])

# Hidden layer weights
W1 = np.array([
    [0.2, 0.3],
    [0.4, 0.1]
])

# Output layer weights
W2 = np.array([
    [0.5],
    [0.6]
])

# Biases
b1 = np.array([[0.0, 0.0]])
b2 = np.array([[0.0]])

# Learning rate
learning_rate = 0.1

In [4]:
# Hidden layer
hidden_input = np.dot(x, W1) + b1
hidden_output = sigmoid(hidden_input)

# Output layer
final_input = np.dot(hidden_output, W2) + b2
prediction = sigmoid(final_input)

print("Hidden Layer Output")
print(hidden_output)

print("\nPredicted Output")
print(prediction)

Hidden Layer Output
[[0.549834   0.57444252]]

Predicted Output
[[0.65012359]]


In [5]:
loss = np.mean((y - prediction) ** 2)

print("\nMean Squared Error")
print(loss)


Mean Squared Error
0.12241350174855715


In [6]:
# Output layer error
output_error = prediction - y

# Gradient at output
d_output = output_error * sigmoid_derivative(prediction)

# Gradient for W2
dW2 = np.dot(hidden_output.T, d_output)

# Hidden layer error
hidden_error = np.dot(d_output, W2.T)

# Hidden layer gradient
d_hidden = hidden_error * sigmoid_derivative(hidden_output)

# Gradient for W1
dW1 = np.dot(x.T, d_hidden)

In [7]:
print("Gradient of W1")
print(dW1)

print("\nGradient of W2")
print(dW2)

Gradient of W1
[[-0.00984917 -0.01167297]
 [ 0.          0.        ]]

Gradient of W2
[[-0.04375794]
 [-0.04571638]]


In [8]:
W1 = W1 - learning_rate * dW1

W2 = W2 - learning_rate * dW2

In [9]:
b1 = b1 - learning_rate * d_hidden

b2 = b2 - learning_rate * d_output

In [10]:
print("Updated W1")
print(W1)

print("\nUpdated W2")
print(W2)

print("\nUpdated b1")
print(b1)

print("\nUpdated b2")
print(b2)

Updated W1
[[0.20098492 0.3011673 ]
 [0.4        0.1       ]]

Updated W2
[[0.50437579]
 [0.60457164]]

Updated b1
[[0.00098492 0.0011673 ]]

Updated b2
[[0.00795839]]


In [11]:
hidden_input = np.dot(x, W1) + b1
hidden_output = sigmoid(hidden_input)

final_input = np.dot(hidden_output, W2) + b2
prediction = sigmoid(final_input)

new_loss = np.mean((y - prediction) ** 2)

print("Prediction After Weight Update")
print(prediction)

print("\nNew Loss")
print(new_loss)

Prediction After Weight Update
[[0.65320651]]

New Loss
0.12026572214875438


In [12]:
print("Old Loss :", loss)
print("New Loss :", new_loss)

if new_loss < loss:
    print("\nTraining Successful")
else:
    print("\nLoss Did Not Reduce")

Old Loss : 0.12241350174855715
New Loss : 0.12026572214875438

Training Successful
